export const LOAD_MAP = 'LOAD_MAP';
export const LOAD_PLAYERS = 'LOAD_PLAYERS';
export const UPDATE_SAVED_PLAYERS = 'UPDATE_SAVED_PLAYERS';
export const UPDATE_SAVED_MAPS = 'UPDATE_SAVED_MAPS';
export const ADD_CHAT = 'ADD_CHAT';
export const UPDATE_SAVED_MONSTERS = 'UPDATE_SAVED_MONSTERS';
export const LOAD_HITPOINTS = 'LOAD_HITPOINTS';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const LOAD_SAVED_EVENTS = 'LOAD_SAVED_EVENTS'
export const LOAD_EVENTS = 'LOAD_EVENTS'
export const LOAD_ACTIVE = 'LOAD_ACTIVE'


